### ISSUE TITLE
..Again..

### ISSUE THREAD

**Issue by skind** [Vycka/ElasticSearch.Client#4]
..everything is working perfect - but now a simple question/task occured:
 Is it possible with your Lib (and how to do)  to retrieve the whole 'dataset' when querying against
a unique Id?
Thank you very much for answering!
skind

**Comment by Vycka** [comment]
Hey, what do you mean by whole dataset? Maybe an example?

**Comment by skind** [comment]
thankx for fast responding. 
Let's compare it with a simple database with one table. The 'dataset' is a complete row (all columns). This is colloquially known as a dataset in Germany. I hope this helps.
Best regards, skind

**Comment by Vycka** [comment]
I assume, you know, how to build a filtered query for those concrete records you want, but instead of executing it as aggregate query, you execute it as normal query: client.ExecuteQuery(queryBuilder);

https://github.com/Vycka/ElasticSearch.Client/blob/master/src/ElasticSearch.Playground/Samples/Term.cs
By default, results will be filled into dynamic structure [ public class ElasticSearchResult : SearchResult<dynamic> ]

But you can also do ExecuteQuery&lt;TResult&gt;(queryBuilder), and provide your custom made model and and it should fit like a glove (thx to newton json)

**Comment by skind** [comment]
..ohh damn, now it works - excuse me, i forgot to Switch from client.ExecuteAggregate to client.ExecuteQuery.
Best Regards, skind
